### PR TITLE
Eagerly clean module cache when using argon2.hash

### LINKED ISSUE #13438: High memory consumption from Crypto Wallets
## Steps to Reproduce
   1. Clean profile, install crypto wallets
   2. Pre account creation, import, note relatively low memory usage of the Crypto Wallets extension (<=100mb)
   3. Create an account

## Actual result:
   4. On the seed phrase recovery screen, note the very high memory usage (>=550mb)
   5. Note the continued high memory usage while using the extension, with spikes up after unlocking
image (1)

## Expected result:
Much more reasonable memory usage
Screen Shot 2021-01-07 at 8 18 13 PM    

## Reproduces how often: 
100%

### PR DESCRIPTION
**Pull request by marshall**
Fixes brave/brave-browser#13438

The heap that's allocated for argon2-wasm ends up living in the module.exports, which is cached so require('..') is faster. Since we are allocating 500MB for hashing, it means creation of a new wallet or unlocking will holding onto an add'l 500MB after hashing, which we probably don't want!

the best solution would be to do this purely in native C and manage the heap directly, however since we're moving to BIP39, there probably isn't much reason to go that way

/cc @ryanml @diracdeltas

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -18,11 +17,27 @@ const keyringTypes = [
   HdKeyring
 ]
 
-const ARGON2_TYPE = argon2.types.Argon2id
 const KEY_LENGTH = 32 // default key length in bytes
 const TextEncoder = window.TextEncoder || require('util').TextEncoder
 const TextDecoder = window.TextDecoder || require('util').TextDecoder
 
+
+const MODULE_CACHE = new WeakRef(arguments[5])
```
Comment (diracdeltas) [inline index.js]: this causes tests to fail because `WeakRef` doesn't exist in Node: https://travis-ci.com/github/brave/KeyringController/builds/213585178#L528. `window.WeakRef` might work. otherwise it probably needs to be polyfilled for the sake of tests.

Comment (marshall) [reply index.js]: oof, good catch! I'll fix it right up

**Comment by marshall** [comment]
@diracdeltas this is ready for another review. I'm using the npm `weak` module, and needed to bump up the test timeout to 10sec because `argon2-wasm` memory allocates lazily anytime we hash now, slowing down that code path a bit

File: index.js [hunk 2]
```diff
@@ -18,11 +17,54 @@ const keyringTypes = [
...
 const TextEncoder = window.TextEncoder || require('util').TextEncoder
 const TextDecoder = window.TextDecoder || require('util').TextDecoder
 
+
+let moduleCacheTmp = arguments[5]
+const MODULE_CACHE = moduleCacheRef()
+
+function moduleCacheRef() {
+  if (window.WeakRef) {
+    let ref = new WeakRef(moduleCacheTmp)
```
Comment (diracdeltas) [inline index.js]: nit: `window.WeakRef` for consistency

File: index.js [hunk 3]
```diff
@@ -18,11 +17,54 @@ const keyringTypes = [
   HdKeyring
 ]
 
-const ARGON2_TYPE = argon2.types.Argon2id
 const KEY_LENGTH = 32 // default key length in bytes
 const TextEncoder = window.TextEncoder || require('util').TextEncoder
 const TextDecoder = window.TextDecoder || require('util').TextDecoder
 
+
```
Comment (diracdeltas) [inline index.js]: nit: extra blank line

File: index.js (hunk 2 above)
Comment (diracdeltas) [reply index.js]: also this can be const instead of let

File: index.js [hunk 4]
```diff
@@ -18,11 +17,54 @@ const keyringTypes = [
...
+let moduleCacheTmp = arguments[5]
+const MODULE_CACHE = moduleCacheRef()
+
+function moduleCacheRef() {
```
Comment (diracdeltas) [inline index.js]: nit: space before the parens

File: index.js [hunk 5]
```diff
@@ -18,11 +17,54 @@ const keyringTypes = [
...
+  try {
+    const weak = require('weak')
+    let ref = {
+      _ref: weak(moduleCacheTmp),
+      deref() {
+        return weak.isDead(this._ref) ? null : this._ref
+      }
+    }
+
+    moduleCacheTmp = null;
```
Comment (diracdeltas) [inline index.js]: no need for semicolon

File: index.js [hunk 6]
```diff
@@ -18,11 +17,54 @@ const keyringTypes = [
...
+    return ref
+  } catch (e) {
+  }
+
+  return {
+    deref() { return moduleCacheTmp }
```
Comment (diracdeltas) [inline index.js]: nit: space before the parens

File: index.js [hunk 7]
```diff
@@ -18,11 +17,54 @@ const keyringTypes = [
...
+  }
+}
+
+function clearFromCache(instance) {
```
Comment (diracdeltas) [inline index.js]: nit: space before the parens

File: index.js [hunk 8]
```diff
@@ -18,11 +17,54 @@ const keyringTypes = [
...
+  let moduleCache = MODULE_CACHE.deref()
+  if (!moduleCache) {
+    return
+  }
+
+  for (let key in moduleCache) {
+    if (moduleCache[key].exports == instance) {
```
Comment (diracdeltas) [inline index.js]: should be === ?

File: index.js [hunk 9]
```diff
@@ -18,11 +17,54 @@ const keyringTypes = [
...
+  } catch (e) {
+  }
+
+  return {
+    deref() { return moduleCacheTmp }
+  }
+}
+
+function clearFromCache(instance) {
+  let moduleCache = MODULE_CACHE.deref()
```
Comment (diracdeltas) [inline index.js]: this can also be const

**Review by diracdeltas — APPROVED** [review]
lgtm; let me know when i should do an npm release for this

**Comment by marshall** [comment]
@diracdeltas would you mind merging and publishing? I want to test with an updated dependency from `ethereum-remote-client` (also, I don't have merge permission :)

**Comment by diracdeltas** [comment]
@marshall it's been published as 5.4.3
